### PR TITLE
Best score is now saved to cookies

### PR DESCRIPTION
**Pull request by mantevian**
Best score is now displayed next to current score and stored into cookies. Fixes issue #6 

screenshot

### CODE REVIEW

**Review by devsargam — COMMENTED** [review]
Can you implement this in localstorage as it is better for this purpose?

**Comment by devsargam** [comment]
@mantevian why did you force pushed or am I doing something wrong?

**Comment by mantevian** [comment]
I messed up a bit, gonna open a new PR, you can delete this one

**Comment by devsargam** [comment]
alright make sure you don't do something wrong :clinking_glasses:

**Pull request closed without merging**
