### PR TITLE
Added top, down, up, bottom and pause buttons to the game

### PR DESCRIPTION
**Pull request by annupriy**
Fixes issue #57 

Added these buttons so that players can play the game without a keyboard.

# Demo Video:-
https://user-images.githubusercontent.com/96621669/196031011-890d550e-26c3-4551-bc56-45c3551934f7.mov

### CODE REVIEW

**Comment by devsargam** [comment]
@annupriy did you push the correct code??? It's not working on my device.

**Review by devsargam — CHANGES_REQUESTED** [review]
Move button and cross button are not working

**Comment by devsargam** [comment]
@annupriy also the issue was to resolve responsiveness of website which is not there yet making this commit useless. Can you fix that??? :pray:

**Comment by annupriy** [comment]
> @annupriy also the issue was to resolve responsiveness of website which is not there yet making this commit useless. Can you fix that??? 🙏

I rose that issue in beginning but you said that wasn't necessary because it still won't be playable on small devices after that I asked If I could add buttons and you agreed. That's why I added the buttons instead.

Is it fine if I create 2 issues separately for both features i.e. adding buttons and making the website responsive?

**Comment by devsargam** [comment]
@annupriy the current issue is that the game controls don't work at all [click here](https://deploy-preview-65--snakeinjs.netlify.app/)
Could you fix that first and then work on mobile optimization?

**Comment by annupriy** [comment]
@devsargam Please review it once!

**Comment by devsargam** [comment]
@annupriy your commit is making the game look worse then it is currently. Also I meant to say the buttons are not functional at all
image

**Comment by annupriy** [comment]
The buttons are perfectly working for me. I rechecked it many times after deploying. You just have to click on them. Anyway, no problem @devsargam, you can unassign me because I don't think I will be able to add buttons, enhance CSS and make it responsive all at one time in one PR.

**Comment by devsargam** [comment]
@annupriy thank you for your valuable time and contribution. But I couldn't make it work on my device at all. Maybe it's related to my browser. But I won't be able to merge. Still thanks a lot :pray: 
image

**Pull request closed without merging**
