### PR TITLE
Add audio turn on/off button

### PR DESCRIPTION
**Pull request by Jflyer45**

### CODE REVIEW

**Comment by devsargam** [comment]
Can you change the implementation of audio button from it's own function to a method of `Board`?

**Comment by Jflyer45** [comment]
Would it be fine to just set it up in the constructor?

image

**Comment by devsargam** [comment]
It would be fine.
Use => instead of regular functions just to make things consistent
If you are facing difficulties in classes I'll do it myself.

**Comment by Jflyer45** [comment]
Let me know if there is anything else

**Comment by devsargam** [comment]
Things I want to see changed:
> Refactor sound on/off logic into it's own method like `Board:handleAudio`
> reference `audioButton` with `this.audioButton` like other elements
> Use Prettier formatting. You can get it from vscode marketpace if you use it.

**Comment by devsargam** [comment]
> Things I want to see changed:
> 
> > Refactor sound on/off logic into it's own method like `Board:handleAudio`
> > reference `audioButton` with `this.audioButton` like other elements
> > Use Prettier formatting. You can get it from vscode marketpace if you use it.

@Jflyer45 Can you refactor code as per the requirement?

**Comment by Jflyer45** [comment]
Here we go. I tried putting in a function before and it wasn't working, got it now.

**Comment by Jflyer45** [comment]
Let me look at making audio button a attribute of board

**Comment by devsargam** [comment]
LGTM

**Comment by devsargam** [comment]
Thanks for everything you've done. Do you want to implement some more features?

**Comment by devsargam** [comment]
> Yeah, probably will later this week. Thanks for maintaining the repo and being a part of Octoberfest.
Sweet, I'll try to figure more issues and list them on issues tab. :clinking_glasses:

**Pull request merged**
