### PR TITLE
add splash title screen

### PR DESCRIPTION
**Pull request by thevinitgupta**
- Add splash title screen with features like Start/Resume game
- Also shows leaderboard with the best score

snakeoverlay

### CODE REVIEW

**Review by devsargam — CHANGES_REQUESTED** [review]
@thevinitgupta there are few changes that I want
* Whenever user presses `escape` after starting the game it should display "press resume to play" instead of "press start to play"
image
* Implement some styles on select element
* Add sound on and sound off feature in the title screen
* Make title with some catchy color which looks like the theme of the game
Feel free to hit me up if you have any problems or queries

**Comment by devsargam** [comment]
https://github.com/devsargam/SnakeGame/issues/14

**Comment by thevinitgupta** [comment]
Sure I will work on this.

**Comment by thevinitgupta** [comment]
I have made all the changes requested
The style of the options changes with the changing theme : 
classictheme
pinktheme

Added the sounds to toggling splash screen

**Comment by devsargam** [comment]
@thevinitgupta everything looks good but add option to turn on and off sound just like theme and difficulty. You may use toggle button like below and everything becomes fine.
image

**Comment by devsargam** [comment]
@thevinitgupta also make sure you use yarn instead of npm and remove package-lock.json.

**Comment by thevinitgupta** [comment]
I have added the sound toggle button on the title screen

**Review by devsargam — APPROVED** [review]

**Comment by devsargam** [comment]
@thevinitgupta well done. Everything looks very polished! :tada:

**Pull request merged**
