### PR TITLE
Fix Score-Issue

### LINKED ISSUE #44: website is not reflexive,
there should be score board at corner of the game that should display score.

### PR DESCRIPTION
**Pull request by xstable**
closes #44

### CODE REVIEW

**Comment by devsargam** [comment]
@xstable does your commit really fix the issue?
image

**Review by devsargam — CHANGES_REQUESTED** [review]
This does not work great on all devices/browsers

**Comment by xstable** [comment]
I was only able to check it at my 14' screen.
The missing "blue" background is another part, but also easy to fix.
Let me fix this.

**Comment by devsargam** [comment]
@xstable go for it!

**Review by devsargam — APPROVED** [review]
LGTM

**Pull request merged**
