### PR TITLE
Added instruction on "How to Play"

### PR DESCRIPTION
**Pull request by jatin00000**

### CODE REVIEW

**Comment by devsargam** [comment]
@jatin00000 good job. But just saying click this arrow and that arrow will not make people understand how this game works/
Can you add a seperate help button which users can click to under how this game works.
* What is the main idea of game
* What is the goal of game
* Describe about controls

**Comment by jatin00000** [comment]
Sure!! I will soon show progress.

**Comment by devsargam** [comment]
@jatin00000 there are multiple errors in your code refactor them ASAP

**Comment by jatin00000** [comment]
I am creating a control and objective panel like when appear on pressing Escape key. It will be ready soon.

**Comment by devsargam** [comment]
@jatin00000 okayy dude,Good luck

**Comment by devsargam** [comment]
@jatin00000 what are you doing keeping css in javascript file????

**Pull request closed without merging**
