### PR TITLE
Added Game Over modal functionality

### PR DESCRIPTION
**Pull request by thisisamish**
### This PR will solve issue #47.
I have added a modal in the index.html file that displays the game over message in the middle of the screen. Since the game over message display is being handled by this modal, I have removed the game over div.
Please let me know if there are any issues still remaining or if I should explain the changes any further.
Also, this is my first PR ever! :)

### CODE REVIEW

**Comment by devsargam** [comment]
@thisisamish as this is your first pr I'll try my best to help you!
I don't think you have much experience contributing to opensource but generally you need to open an issue or as the owner of repo or the issue creater to assign you the issue and only then start working on it. This is your first one so keep it in mind from now on.

**Comment by devsargam** [comment]
@thisisamish in my 14' laptop I don't think thats how the modal should look. Could you fix it by making the font slightly smaller or by making the modal slightly bigger
image

**Comment by thisisamish** [comment]
Yeah, sure. I'm on it.
Also, thank you for assigning this issue to me and tagging it with hacktoberfest-accepted. I didn't have a good idea of how all this works so it was really cool of you to do this. :)

**Comment by devsargam** [comment]
@thisisamish feel free to star this project :clinking_glasses:

**Comment by thisisamish** [comment]
sure. would be happy to. 😊

**Comment by thisisamish** [comment]
Hey @devsargam, I have made the modal slightly bigger and the text slightly smaller. I tested it on a 14" laptop screen in Chrome browser and it is working fine now. Could you please check at your end?

**Comment by devsargam** [comment]
@thisisamish looks fine.

**Comment by devsargam** [comment]
fixes: #47

**Pull request merged**
