### PR TITLE
add wallsCollider into snake

### PR DESCRIPTION
**Pull request by hiyokun-d**
modified:   src/scripts/classes/betterboard.js
	modified:   src/scripts/classes/snake.js
	modified:   yarn.lock

## Checklist before requesting a review
- [x] I have performed a self-review of my code
- [ ] I assure there is no similar/duplicate pull request regarding same issue

### CODE REVIEW

**Comment by devsargam** [comment]
@hiyokun-d please, mention what changes you have made!

**Comment by devsargam** [comment]
@hiyokun-d also the collision with walls thing is still not working if that feature is complete

**Comment by hiyokun-d** [comment]
> @hiyokun-d also the collision with walls thing is still not working if that feature is complete

I just set it to work in hard difficulty so if in the other difficulty it won't work so it will be challenging

**Comment by hiyokun-d** [comment]
> @hiyokun-d please, mention what changes you have made!

Sorry, I forgot to put the changes I'm just modified the snake class also simpleboard and I forgot what I add in that file sorry

**Comment by devsargam** [comment]
@hiyokun-d thanks for your contribution

**Pull request merged**
