### PR TITLE
Improved Overlay Interface

### PR DESCRIPTION
**Pull request by aliaquintero**
- imported fonts for improved UI
- added cursor pointer to overlay selections 
- change toggle button text to "start game" 
- fixed some minor spelling formatting in HTML
- change toggle button hover to darker and faster transition
- changed container width for better responsiveness in mobile
- rounded overlay borders more for improved UI
- changed sounds toggle background to blue to match UI
- removed border radius on overlay background because it didn't look right
- fixed difficulty order to easy, medium, hard

Screen Shot 2022-10-12 at 5 12 24 PM

if this could be accepted for hacktoberfest (or marked hacktoberfest-accepted) thank you!

### CODE REVIEW

**Comment by devsargam** [comment]
@aliaquintero looks great. You have nice frontend skills.

**Comment by devsargam** [comment]
@aliaquintero there is just a slight issue. When someone pauses the game, you still get start game but in reality it should say resume or play. Can you fix that

**Comment by aliaquintero** [comment]
> @aliaquintero there is just a slight issue. When someone pauses the game, you still get start game but in reality it should say resume or play. Can you fix that

got it! added a couple of fixes as well: 
- shortened "select theme/select difficulty" to just theme/difficulty
- changed board height to 85vh to try and prevent runoff 
- changed overlay button to say "resume" when paused 
- accidentally modified info class without removing changes, had to go back and fix :)

**Comment by devsargam** [comment]
@aliaquintero there is still a small issue. Using firefox on linux. Could you fix the gaps issue please. :smiley_cat: 
image

**Comment by aliaquintero** [comment]
> @aliaquintero there is still a small issue. Using firefox on linux. Could you fix the gaps issue please. 😺 image

hmm, it's not showing me that issue but if i try overflow: hidden on the board div would that work without hurting game functionality?

**Comment by devsargam** [comment]
@aliaquintero the reason it might not be shown in your browser maybe because you are currently using windows os. In linux it is zoomed out to about 80% of that in windows so try making your browser on 80% zoom.
The current issue is be due to in #board
```css
min-height: 85vh;
```

**Comment by aliaquintero** [comment]
@devsargam i'll go ahead and remove it since i added it unrelated to this pull request and that can be a good fix later!

**Comment by devsargam** [comment]
@aliaquintero LGTM! Feel free to contribute on something else in this project. Your commits has made this game way better. :clinking_glasses:

**Pull request merged**
